- name: variables from file
  hosts: localhost
  connection: local
  vars_files:
    - course.yaml
  tasks: 
    - name: print course info
      ansible.builtin.debug:
        msg: "Hello {{ COURSE }}, duration is {{ HOURS }}, trainer is {{ TRAINER }}, {{ GREETINGS }}"
