- name: prompts
  hosts: local
  connection: local
  vars_prompt: 
  - name: USERNAME
    prompt: enter username here
    private: true
  - name: PASSWORD
    prompt: enter password here
    private: true
  tasks:
  - name: prompt vars
    ansible.builtin.debug:
      msg: "username is: {{ USERNAME }}, password is : {{ PASSWORD }}"

   