- name: reffering variable file
  hosts: local
  connection: localhost
  vars_file:
  - course.yaml
  tasks: 
  - name: reffering vars
    ansible.builtin.debug:
      msg: "hello {{ COURSE }},duration is {{ HOURS }}, trainer is {{ TRAINER }},{{ GREETINGS }}"
